services:
  gfm-biomassters:
    image: gfm-biomassters:latest
    build: .
    stdin_open: true
    tty: true
    volumes:
       - /workspace/Denys/biomassters/BioMassters-extracted/:/data/
       - /workspace/Denys/biomassters/gfm-biomassters-terratorch/gfm-biomassters-output/:/output/
       - /workspace/Denys/biomassters/gfm-biomassters-terratorch/gfm-biomassters/:/opt/app-root/src/terratorch/
    shm_size: '2gb'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["2"]
              capabilities: [gpu]
