services:
  terratorch:
    image: gfm-biomassters:latest
    build: .
    stdin_open: true
    tty: true
    volumes:
       - /workspace/Denys/biomassters/BioMassters-extracted/:/data/
       - /workspace/Denys/biomassters/gfm-biomassters-terratorch/gfm-biomassters-output/:/output/
       - /workspace/Denys/biomassters/paper_results/baseline/:/baseline/
       - /workspace/Denys/biomassters/gfm-biomassters-terratorch/gfm-biomassters/:/opt/app-root/src/terratorch/
    shm_size: '16gb'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0", "1", "2", "3", "5"]
              capabilities: [gpu]
