# lightning.pytorch==2.1.1
seed_everything: 0
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: 16-mixed
  logger:
    class_path: TensorBoardLogger
    init_args:
      save_dir: <your_path_here>/torchgeo_eurosat
      name: generic
  callbacks:
    - class_path: RichProgressBar
    - class_path: LearningRateMonitor
      init_args:
        logging_interval: epoch

  max_epochs: 200
  check_val_every_n_epoch: 1
  log_every_n_steps: 50
  enable_checkpointing: true
  default_root_dir: <your_path_here>/torchgeo_eurosat

data:
  class_path: GenericNonGeoClassificationDataModule
  init_args:
    train_transform:
      - class_path: albumentations.augmentations.geometric.resize.Resize
        init_args:
          height: 224
          width: 224
      - class_path: ToTensorV2
    test_transform:
      - class_path: albumentations.augmentations.geometric.resize.Resize
        init_args:
          height: 224
          width: 224
      - class_path: ToTensorV2
    val_transform:
      - class_path: albumentations.augmentations.geometric.resize.Resize
        init_args:
          height: 224
          width: 224
      - class_path: ToTensorV2
    batch_size: 32
    num_workers: 12
    dataset_bands:
      - 1
      - BLUE
      - GREEN
      - RED
      - 5
      - 6
      - 7
      - 8
      - 9
      - NIR_NARROW
      - SWIR_1
      - SWIR_2
    output_bands:
      - BLUE
      - GREEN
      - RED
      - NIR_NARROW
      - SWIR_1
      - SWIR_2
    rgb_indices:
      - 0
      - 1
      - 2
    train_data_root: /dccstor/geofm-pre/EuroSat/ds/images/remote_sensing/otherDatasets/sentinel_2/tif/
    test_data_root: /dccstor/geofm-pre/EuroSat/ds/images/remote_sensing/otherDatasets/sentinel_2/tif/
    val_data_root: /dccstor/geofm-pre/EuroSat/ds/images/remote_sensing/otherDatasets/sentinel_2/tif/
    train_split: /dccstor/geofm-pre/EuroSat/eurosat-train.txt
    test_split: /dccstor/geofm-pre/EuroSat/eurosat-test.txt
    val_split: /dccstor/geofm-pre/EuroSat/eurosat-val.txt
    ignore_split_file_extensions: True
    allow_substring_split_file: False
    means:
      - 1118.24399958
      - 1042.92983953
      - 947.62620298
      - 732.08340178
      - 1118.92391149
      - 2594.14080798
    stds:
      - 333.00778264
      - 395.09249139
      - 593.75055589
      - 404.91978886
      - 761.30323499
      - 1231.58581042
    num_classes: 10

model:
  class_path: ClassificationTask
  init_args:
    model_args:
      decoder: IdentityDecoder
      pretrained: true
      backbone: prithvi_swin_B
      backbone_drop_path_rate: 0.3
      # backbone_window_size: 8
      head_dim_list:
        - 384
        - 128
      bands:
        - BLUE
        - GREEN
        - RED
        - NIR_NARROW
        - SWIR_1
        - SWIR_2
      num_frames: 1
      num_classes: 10
      head_dropout: 0.1
    loss: ce
    freeze_backbone: false
    freeze_decoder: false
    model_factory: PrithviModelFactory
optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 1.e-4
    weight_decay: 0.05
lr_scheduler:
  class_path: ReduceLROnPlateau
  init_args:
    monitor: val/loss
