site_name: TerraTorch
theme:
  name: material
  palette:
    scheme: slate
  features:
    - content.code.copy
    - content.code.select
    - navigation.tabs
plugins:
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          paths: [src] # search packages in the src folde
          options:
            show_root_heading: true
extra:
  version:
    provider: mike

repo_url: https://github.com/IBM/terratorch
nav:
  - index.md
  - Getting Started: quick_start.md
  - Components:
    - Tasks: tasks.md
    - Modekls: models.md
    - Data: data.md
  - For Developers: architecture.md
  - Examples: examples.md
  - FAQ: faq.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
