site_name: TerraTorch
theme:
  name: readthedocs
  logo: https://github.com/user-attachments/assets/f8c9586f-6220-4a53-9669-2aee3300b492" 
  palette:
    scheme: slate
  features:
    - content.code.copy
    - content.code.select
    - navigation.tabs
plugins:
  - search 
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          paths: [src] # search packages in the src folde
          options:
            show_root_heading: true
              #extra:
              #  version:
              #    provider: mike

site_url: https://ibm.github.io/terratorch/
repo_url: https://github.com/IBM/terratorch
nav:
  - index.md
  - Getting Started: quick_start.md
  
  - Examples: examples.md 
  - Glossary: glossary.md
  - License: license.md
  - Contributing: contributing.md
  - Components:
    - Architecture Overview: architecture.md
    - Tasks: tasks.md
    - Models: models.md
    - Data: data.md
    - Registries: registry.md
    - EncoderDecoderFactory: encoder_decoder_factory.md
    #- FAQ: faq.md

markdown_extensions:
  - toc:
      permalink: "#"
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
