data:
  class_path: terratorch.datamodules.GenericNonGeoSegmentationDataModule
  init_args:
    allow_substring_split_file: true
    batch_size: 16
    constant_scale: 0.0001
    dataset_bands:
    - RED
    - GREEN
    - BLUE
    - NIR_NARROW
    - SWIR_1
    - SWIR_2
    drop_last: true
    expand_temporal_dimension: false
    ignore_split_file_extensions: true
    img_grep: '*_S2Hand.tif'
    label_grep: '*_LabelHand.tif'
    means:
    - 0.107582
    - 0.13471393
    - 0.12520133
    - 0.3236181
    - 0.2341743
    - 0.15878009
    num_classes: 2
    num_workers: 8
    output_bands:
    - BLUE
    - GREEN
    - RED
    - NIR_NARROW
    - SWIR_1
    - SWIR_2
    reduce_zero_label: false
    rgb_indices:
    - 2
    - 1
    - 0
    stds:
    - 0.07145836
    - 0.06783548
    - 0.07323416
    - 0.09489725
    - 0.07938496
    - 0.07089546
    test_data_root: /home/jalmeida/Datasets/senfloods/v1.1/data/flood_events/HandLabeled/S2Hand
    test_label_data_root: /home/jalmeida/Datasets/senfloods/v1.1/data/flood_events/HandLabeled/LabelHand
    test_split: /home/jalmeida/Datasets/senfloods/v1.1/splits/flood_handlabeled/flood_test_data.txt
    train_data_root: /home/jalmeida/Datasets/senfloods/v1.1/data/flood_events/HandLabeled/S2Hand
    train_label_data_root: /home/jalmeida/Datasets/senfloods/v1.1/data/flood_events/HandLabeled/LabelHand
    train_split: /home/jalmeida/Datasets/senfloods/v1.1/splits/flood_handlabeled/flood_train_data.txt
    val_data_root: /home/jalmeida/Datasets/senfloods/v1.1/data/flood_events/HandLabeled/S2Hand
    val_label_data_root: /home/jalmeida/Datasets/senfloods/v1.1/data/flood_events/HandLabeled/LabelHand
    val_split: /home/jalmeida/Datasets/senfloods/v1.1/splits/flood_handlabeled/flood_valid_data.txt
model:
  class_path: terratorch.tasks.SemanticSegmentationTask
  init_args:
    aux_heads:
    - decoder: FCNDecoder
      decoder_args:
        decoder_channels: 256
        decoder_in_index: -1
        decoder_num_convs: 2
        head_dropout: 0.1
      name: aux_head
    aux_loss:
      aux_head: 1.0
    freeze_backbone: false
    freeze_decoder: false
    ignore_index: -1
    loss: ce
    lr: 0.001
    model_args:
      backbone: prithvi_vit_100
      backbone_checkpoint_path: /home/jalmeida/checkpoints/epoch-725-loss-0.0365.pt
      backbone_decoder_depth: 8
      backbone_decoder_embed_dim: 512
      backbone_decoder_num_heads: 16
      backbone_embed_dim: 768
      backbone_in_chans: 6
      backbone_mlp_ratio: 4
      backbone_num_frames: 1
      backbone_num_heads: 12
      backbone_patch_size: 16
      backbone_pretrain_img_size: 512
      bands:
      - BLUE
      - GREEN
      - RED
      - NIR_NARROW
      - SWIR_1
      - SWIR_2
      decoder: FCNDecoder
      decoder_channels: 256
      decoder_num_convs: 4
      head_channel_list:
      - 256
      head_dropout: 0.1
      in_channels: 6
      num_classes: 2
      num_frames: 1
      pretrained: false
    model_factory: PrithviModelFactory
    optimizer: Adam
    plot_on_val: 10
out_dtype: int16
seed_everything: 0
trainer:
  accelerator: auto
  accumulate_grad_batches: 1
  barebones: false
  check_val_every_n_epoch: 1
  detect_anomaly: false
  devices: auto
  enable_checkpointing: true
  fast_dev_run: false
  inference_mode: true
  log_every_n_steps: 50
  logger: false
  max_epochs: 200
  max_steps: -1
  num_nodes: 1
  overfit_batches: 0.0
  precision: 16-mixed
  reload_dataloaders_every_n_epochs: 0
  strategy: auto
  sync_batchnorm: false
  use_distributed_sampler: true
