ignore: null
model_args:
  decoder: FCNDecoder
  pretrained: true
  backbone: prithvi_vit_100
  backbone_pretrain_img_size: 512
  backbone_embed_dim: 768
  backbone_num_heads: 12
  backbone_decoder_depth: 8
  backbone_decoder_num_heads: 16
  backbone_decoder_embed_dim: 512
  backbone_mlp_ratio: 4
  backbone_patch_size: 16
  backbone_in_chans: 6
  backbone_num_frames: 1
  backbone_checkpoint_path: /home/jalmeida/checkpoints/epoch-725-loss-0.0365.pt
  decoder_channels: 256
  in_channels: 6
  bands:
  - BLUE
  - GREEN
  - RED
  - NIR_NARROW
  - SWIR_1
  - SWIR_2
  num_frames: 1
  num_classes: 2
  head_dropout: 0.1
  decoder_num_convs: 4
  head_channel_list:
  - 256
model_factory: PrithviModelFactory
loss: ce
aux_heads:
- name: aux_head
  decoder: FCNDecoder
  decoder_args:
    decoder_channels: 256
    decoder_in_index: -1
    decoder_num_convs: 2
    head_dropout: 0.1
aux_loss:
  aux_head: 1.0
class_weights: null
ignore_index: -1
lr: 0.001
optimizer: Adam
optimizer_hparams: null
scheduler: null
scheduler_hparams: null
freeze_backbone: false
freeze_decoder: false
plot_on_val: 10
class_names: null
tiled_inference_parameters: null
