# lightning.pytorch==2.1.1
seed_everything: 0
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: 16-mixed
  logger: true
               
  callbacks:
    - class_path: RichProgressBar
    - class_path: LearningRateMonitor
      init_args:
        logging_interval: epoch
    # ---- Early stop if ----
    - class_path: EarlyStopping
      init_args:
        monitor: val/loss
        patience: 20
     # ---- Early stop endif ----
    - class_path: ModelCheckpoint
      init_args:
        dirpath: /geotunes/tune-tasks/geotune-kzgbaa934nkm4vwhssrxtr/
        mode: min
        monitor: val/loss
        filename: best-state_dict-{epoch:02d}
        save_weights_only: True
      
  max_epochs: 2
  check_val_every_n_epoch: 1
  log_every_n_steps: 50
  enable_checkpointing: true
  default_root_dir: /geotunes/tune-tasks/geotune-kzgbaa934nkm4vwhssrxtr

data:
  class_path: terratorch.datamodules.GenericNonGeoSegmentationDataModule
  init_args:
    batch_size: 4
    num_workers: 2
    no_label_replace: -1
    no_data_replace: 0
    constant_scale: 1.0
    dataset_bands:
      - '0'
      - '1'
      - '2'

    output_bands:
      - '0'
      - '1'
      - '2'

    rgb_indices:
      - 0
      - 1
      - 2

    train_data_root: /data//geodata-33432b140a5d11f0b5b90a580a8202d8/training_data/
    train_label_data_root: /data//geodata-33432b140a5d11f0b5b90a580a8202d8/labels/
    val_data_root: /data//geodata-33432b140a5d11f0b5b90a580a8202d8/training_data/
    val_label_data_root: /data//geodata-33432b140a5d11f0b5b90a580a8202d8/labels/
    test_data_root: /data//geodata-33432b140a5d11f0b5b90a580a8202d8/training_data/
    test_label_data_root: /data//geodata-33432b140a5d11f0b5b90a580a8202d8/labels/
    train_split: /data//geodata-33432b140a5d11f0b5b90a580a8202d8/split_files/train_data.txt
    test_split: /data//geodata-33432b140a5d11f0b5b90a580a8202d8/split_files/test_data.txt
    val_split: /data//geodata-33432b140a5d11f0b5b90a580a8202d8/split_files/val_data.txt
    img_grep: "*-img.tiff"
    label_grep: "*-lab.tiff"
    means: 
      - 123.9093071640722
      - 123.9890227665175
      - 115.10178152930658

    stds: 
      - 41.39636610977257
      - 38.10232051141904
      - 38.10214500983553

    num_classes: 2
    # ---- train_transform if ----
    # ---- train_transform endif ----

    # if backbone is prithvi-EO-v2
    test_transform:
      - class_path: ToTensorV2
model:
  class_path: terratorch.tasks.SemanticSegmentationTask
  init_args:
    model_args:
      # Old model version configurations
      pretrained: true
      backbone: prithvi_swin_L
      backbone_pretrained_cfg_overlay:
        file: /terratorch/gfm_models/prithvi_swin_L/epoch-94-loss-0.0918.pt
      # backbone_temporal_encoding: true
      backbone_drop_path_rate: 0.3
      backbone_window_size: 7
      num_frames: 1
      head_channel_list:
        - 256

      bands:
        - '0'
        - '1'
        - '2'

       
      decoder: UNetDecoder
      #TODO user provided channels
      decoder_channels: [512, 256, 128, 64]
      num_classes: 2
      head_dropout: 0.1
    
    model_factory: PrithviModelFactory
     
    loss: ce
    plot_on_val: 2
    ignore_index: -1
    freeze_backbone: false
    freeze_decoder: false

    # ---- optimizer start ----
    # ---- optimizer end ----
    
    tiled_inference_parameters: 
      h_crop: 512
      h_stride: 448
      w_crop: 512
      w_stride: 448
      average_patches: True
    
optimizer:
  class_path: torch.optim.Adam
  init_args:
    # ---- Optimizer start if ----
    lr: 6e-05
    
    weight_decay: 0.05
    # ---- Optimizer stop if ----
lr_scheduler:
  class_path: ReduceLROnPlateau
  init_args:
    monitor: val/loss