# lightning.pytorch==2.1.1
seed_everything: 0
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  # precision: 16-mixed
  logger:
    class_path: TensorBoardLogger
    init_args:
      save_dir: <your_path_here>/torchgeo_agb
      name: swin_bs_32
  callbacks:
    - class_path: RichProgressBar
    - class_path: LearningRateMonitor
      init_args:
        logging_interval: epoch
    - class_path: EarlyStopping
      init_args:
        monitor: val/loss
        patience: 20
  max_epochs: 120
  check_val_every_n_epoch: 1
  log_every_n_steps: 20
  enable_checkpointing: true
  default_root_dir: <your_path_here>/torchgeo_agb
data:
  class_path: GenericNonGeoPixelwiseRegressionDataModule
  init_args:
    batch_size: 32
    num_workers: 8
    train_transform:
      - class_path: albumentations.HorizontalFlip
        init_args:
          p: 0.5
      - class_path: albumentations.Rotate
        init_args:
          limit: 30
          border_mode: 0 # cv2.BORDER_CONSTANT
          value: 0
          mask_value: 1
          p: 0.5
      - class_path: ToTensorV2
    dataset_bands:
      - 0
      - BLUE
      - GREEN
      - RED
      - NIR_NARROW
      - SWIR_1
      - SWIR_2
      - 1
      - 2
      - 3
      - 4
    output_bands:
      - BLUE
      - GREEN
      - RED
      - NIR_NARROW
      - SWIR_1
      - SWIR_2
    rgb_indices:
      - 2
      - 1
      - 0
    train_data_root: /dccstor/hhr-weather/latest_filters_all_agb_patches_tts_clipped_0_500/train_images
    train_label_data_root: /dccstor/hhr-weather/latest_filters_all_agb_patches_tts_clipped_0_500/train_labels
    val_data_root: /dccstor/hhr-weather/latest_filters_all_agb_patches_tts_clipped_0_500/val_images
    val_label_data_root: /dccstor/hhr-weather/latest_filters_all_agb_patches_tts_clipped_0_500/val_labels
    test_data_root: /dccstor/hhr-weather/latest_filters_all_agb_patches_tts_clipped_0_500/test_images
    test_label_data_root: /dccstor/hhr-weather/latest_filters_all_agb_patches_tts_clipped_0_500/test_labels
    # img_grep: "*.tif"
    # label_grep: "*.tif"
    means:
      - 385.88501817
      - 714.60615207
      - 658.96267376
      - 3314.57774238
      - 2238.71812558
      - 1250.00982518
    stds:
      - 264.62872
      - 355.62848
      - 504.54855
      - 898.4953
      - 947.22894
      - 828.1297

model:
  class_path: PixelwiseRegressionTask
  init_args:
    model_args:
      decoder: UperNetDecoder
      pretrained: true
      backbone: prithvi_swin_B
      backbone_drop_path_rate: 0.3
      # backbone_window_size: 8
      decoder_channels: 128
      in_channels: 6
      bands:
        - BLUE
        - GREEN
        - RED
        - NIR_NARROW
        - SWIR_1
        - SWIR_2
      num_frames: 1
      head_dropout: 0.5
      head_final_act: torch.nn.ReLU
    loss: rmse
    #aux_heads:
    #  - name: aux_head
    #    decoder: IdentityDecoder
    #    decoder_args:
    #      decoder_out_index: 2
    #      head_dropout: 0,5
    #      head_channel_list:
    #        - 64
    #      head_final_act: torch.nn.ReLU
    #aux_loss:
    #  aux_head: 0.4
    ignore_index: -1
    freeze_backbone: false
    freeze_decoder: false
    model_factory: PrithviModelFactory

    # uncomment this block for tiled inference
    # tiled_inference_parameters:
    #   h_crop: 224
    #   h_stride: 192
    #   w_crop: 224
    #   w_stride: 192
    #   average_patches: true
optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 0.0005
    weight_decay: 0.05
lr_scheduler:
  class_path: ReduceLROnPlateau
  init_args:
    monitor: val/loss
# no way to pass interval: step except without config
# lr_scheduler:
#   class_path: OneCycleLR
#   init_args:
#     max_lr: 0.0005
#     epochs: 120
#     steps_per_epoch: 375 # 6008 / batch_size
#     pct_start: 0.025
#     # interval: step
#     div_factor: 10
#     final_div_factor: 5e4
#     # monitor: val/loss
