apiVersion: v1
kind: Pod
metadata:
  name: terratorch-test
  namespace: geospatial-alpha
  labels:
    app: terratorch-test
spec:
  imagePullSecrets:
    - name: us-icr-pull-secret
  containers:
    - name: terratorch
      image: us.icr.io/gfmaas/terratorch:dev1
      resources:
        limits:
          cpu: '2'
          memory: 26G
          nvidia.com/gpu: '1'
        requests:
          cpu: 1900m
          memory: 24976M
          nvidia.com/gpu: '1'
      imagePullPolicy: Always
      command: ["sleep"]
      args: ["10800"]
      volumeMounts:
      - name: mount-data
        mountPath: /data
      - name: mount-models
        mountPath: /terratorch/gfm_models
      - name: mount-working
        mountPath: /working
      - name: dshm
        mountPath: /dev/shm
  serviceAccountName: internal-mcadder
  volumes:
    - name: mount-data
      persistentVolumeClaim:
        claimName: geoft-service-datasets-pvc
    - name: mount-models
      persistentVolumeClaim:
        claimName: gfm-models-pvc
    - name: mount-working
      persistentVolumeClaim:
        claimName: test-temp-pvc
    - name: dshm
      emptyDir:
        medium: Memory
  restartPolicy: Never
  terminationGracePeriodSeconds: 30

