seed_everything: 0
trainer:
  accelerator: "gpu"
  devices: [0]
  logger: True
  callbacks:
    - class_path: RichProgressBar
    - class_path: LearningRateMonitor
      init_args:
        logging_interval: epoch

  max_epochs: 3
  check_val_every_n_epoch: 1
  log_every_n_steps: 50
  enable_checkpointing: true
  default_root_dir: "/dccstor/geofm-finetuning/geobench/classification_v1.0"
data:
  class_path: MBigEarthNonGeoDataModule
  init_args:
    batch_size: 16
    num_workers: 1
    data_root: "/dccstor/geofm-finetuning/geobench/classification_v1.0"
    bands:
      - "COASTAL_AEROSOL"
      - "RED"
      - "GREEN"
      - "BLUE"
      - "RED_EDGE_1"
      - "RED_EDGE_2"
      - "RED_EDGE_3"
      - "NIR_BROAD"
      - "NIR_NARROW"
      - "WATER_VAPOR"
      - "SWIR_1"
      - "SWIR_2"

model:
  class_path: MultiLabelClassificationTask
  init_args:
    model_args:
      decoder: IdentityDecoder
      pretrained: ResNet18_Weights.SENTINEL2_RGB_MOCO
      backbone: resnet18
      in_channels: 12
      num_classes: 43
    loss: bce
    model_factory: TimmModelFactory
optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 6.e-5
    weight_decay: 0.05
lr_scheduler:
  class_path: ReduceLROnPlateau
  init_args:
    monitor: val/loss
