seed_everything: 0
trainer:
  accelerator: 'gpu'
  devices: [0]
  logger: True # will use tensorboardlogger
  callbacks:
    - class_path: RichProgressBar
    - class_path: LearningRateMonitor
      init_args:
        logging_interval: epoch

  max_epochs: 1
  check_val_every_n_epoch: 1
  log_every_n_steps: 50
  enable_checkpointing: true
  default_root_dir: "/dccstor/geofm-finetuning/geobench/classification_v1.0"
data:
  class_path: MSo2SatNonGeoDataModule
  init_args:
    batch_size: 16
    num_workers: 1
    train_transform:
      - class_path: albumentations.HorizontalFlip
        init_args:
          p: 0.5
      - class_path: albumentations.Rotate
        init_args:
          limit: 30
          border_mode: 0 
          value: 0
          mask_value: 1
          p: 0.5
      - class_path: ToTensorV2
    data_root: "/dccstor/geofm-finetuning/geobench/classification_v1.0"
    bands:
      - "VH_REAL"
      - "RED"
      - "VH_IMAGINARY"
      - "GREEN"
      - "VV_REAL"
      - "BLUE"
      - "VV_IMAGINARY"
      - "VH_LEE_FILTERED"
      - "RED_EDGE_1"
      - "VV_LEE_FILTERED"
      - "RED_EDGE_2"
      - "VH_LEE_FILTERED_REAL"
      - "RED_EDGE_3"
      - "NIR_BROAD"
      - "VV_LEE_FILTERED_IMAGINARY"
      - "NIR_NARROW"
      - "SWIR_1"
      - "SWIR_2"

model:
  class_path: ClassificationTask
  init_args:
    model_args:
      decoder: IdentityDecoder
      pretrained: true
      backbone: prithvi_vit_100
      in_channels: 18
      bands:
        - 0
        - RED
        - 2
        - GREEN
        - 4
        - BLUE
        - 6
        - 7
        - RED_EDGE_1
        - 9
        - RED_EDGE_2
        - 11
        - RED_EDGE_3
        - NIR_BROAD
        - 14
        - NIR_NARROW
        - SWIR_1
        - SWIR_2
      num_classes: 17
    loss: ce
    model_factory: PrithviModelFactory
optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 6.e-5
    weight_decay: 0.05
lr_scheduler:
  class_path: ReduceLROnPlateau
  init_args:
    monitor: val/loss