# lightning.pytorch==2.1.1
seed_everything: 0
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  # precision: bf16
  logger:
    class_path: TensorBoardLogger
    init_args:
      save_dir: /dccstor/geofm-finetuning/carlosgomes/torchgeo_floods
      name: sen1floods11_new_factory
  callbacks:
    - class_path: RichProgressBar
    - class_path: LearningRateMonitor
      init_args:
        logging_interval: epoch

  max_epochs: 50
  check_val_every_n_epoch: 1
  log_every_n_steps: 50
  enable_checkpointing: true
  default_root_dir: /dccstor/geofm-finetuning/carlosgomes/torchgeo_floods
data:
  class_path: terratorch.datamodules.sen1floods11.Sen1Floods11NonGeoDataModule
  init_args:
    batch_size: 8
    num_workers: 8
  dict_kwargs:
    data_root: /dccstor/geofm-finetuning/flood_mapping/sen1floods11/
    bands:
      - 1
      - 2
      - 3
      - 8
      - 11
      - 12
model:
  class_path: terratorch.tasks.SemanticSegmentationTask
  init_args:
    model_args:
      decoder: FCNHead
      backbone_pretrained: True
      backbone: prithvi_vit_300
      backbone_pretrained_cfg_overlay:
        file: /dccstor/geofm-finetuning/pretrain_ckpts/v9_no_sea_subset/mae/checkpoint.pt
      backbone_pretrain_img_size: 512
      decoder_num_convs: 4
      decoder_channels: 256
      decoder_dropout_ratio: 0.1
      backbone_in_channels: 6
      backbone_bands:
        - BLUE
        - GREEN
        - RED
        - NIR_NARROW
        - SWIR_1
        - SWIR_2
      num_frames: 1
      num_classes: 2
      necks:
        - name: ReshapeTokensToImage
        - name: SelectIndices
          indices:
            - -1
    loss: ce
    
    ignore_index: -1
    class_weights:
      - 0.3
      - 0.7
    freeze_backbone: true
    freeze_decoder: false
    model_factory: EncoderDecoderFactory
optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 6.e-5
    weight_decay: 0.05
lr_scheduler:
  class_path: ReduceLROnPlateau
  init_args:
    monitor: val/loss
