seed_everything: 0
trainer:
  accelerator: "gpu"
  devices: [0]
  logger: True # will use tensorboardlogger
  callbacks:
    - class_path: RichProgressBar
    - class_path: LearningRateMonitor
      init_args:
        logging_interval: epoch

  max_epochs: 3
  check_val_every_n_epoch: 1
  log_every_n_steps: 50
  enable_checkpointing: true
  default_root_dir: "/dccstor/geofm-finetuning/geobench/segmentation_v1.0"
data:
  class_path: MChesapeakeLandcoverNonGeoDataModule
  init_args:
    batch_size: 32
    num_workers: 4
    data_root: "/dccstor/geofm-finetuning/geobench/segmentation_v1.0"
    bands:
      - "RED"
      - "GREEN"
      - "BLUE"
      - "NIR"

model:
  class_path: SemanticSegmentationTask
  init_args:
    model_args:
      decoder: unet
      pretrained: imagenet
      in_channels: 4
      backbone: resnet50
      num_classes: 7
    loss: ce
    model_factory: SMPModelFactory
optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 1e-4
    weight_decay: 0.05
lr_scheduler:
  class_path: ReduceLROnPlateau
  init_args:
    monitor: val/loss
